// Copyright © Erickson Lopez. MIT License.
using System;
using System.Text.Json.Serialization;

using EricksonLopez.Outbox.Generated; // namespace generated by [OutboxMessage] source generator
using Sample.OrderService.Domain.Aggregates.OrderAggregate;

// ─────────────────────────────────────────────────────────────────────────────
// OutboxJsonContext
//
// Declare this partial class ONCE in your project. System.Text.Json's own source
// generator completes it at compile time, producing a fully AOT-safe serializer.
//
// The [JsonSerializable] list was auto-generated by looking at the OutboxJsonContext.g.cs
// hint file produced by EricksonLopez.Outbox.SourceGenerators.
//
// To add new message types: apply [OutboxMessage] to the new type, rebuild,
// then copy the new [JsonSerializable] line from OutboxJsonContext.g.cs.
// ─────────────────────────────────────────────────────────────────────────────

namespace Sample.OrderService.Infrastructure;

[JsonSourceGenerationOptions(
    WriteIndented = false,
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(OrderCreatedEvent))]
[JsonSerializable(typeof(OrderConfirmedEvent))]
[JsonSerializable(typeof(BatchTestEvent))]
public partial class OutboxJsonContext : JsonSerializerContext { }



