<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\EricksonLopez.Outbox\EricksonLopez.Outbox.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" />
  </ItemGroup>

  <PropertyGroup>
    <Description>MassTransit integration for EricksonLopez.Outbox. Enables reliable, high-performance, Zero-Reflection, NativeAOT-ready event publishing through MassTransit.</Description>
    <PackageTags>$(PackageTags);masstransit;message-bus;service-bus</PackageTags>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
