// Stryker disable all : Covered by ADR-013. Edge cases, micro-optimizations, logging, and validation strings are not rigorously mutated.
using System;
using System.Buffers;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;

namespace EricksonLopez.Outbox.Serialization;

/// <summary>
/// A strict NativeAOT compatible JSON serializer.
/// It bans runtime reflection completely by requiring a pre-compiled JsonSerializerContext 
/// (which our Incremental Source Generators will provide).
/// </summary>
public sealed class NativeAotJsonSerializer : IOutboxSerializer
{
    private readonly JsonSerializerContext _context;
    private readonly Microsoft.Extensions.ObjectPool.ObjectPool<Utf8JsonWriter> _writerPool;

    /// <summary>
    /// Initializes a new instance of the <see cref="NativeAotJsonSerializer"/> class.
    /// </summary>
    /// <param name="context">The pre-compiled <see cref="JsonSerializerContext"/> containing type info.</param>
    /// <remarks>
    /// For NativeAOT compatibility without IL2026/IL2057 warnings, the provided <paramref name="context"/>
    /// must be generated by the System.Text.Json source generator and include all message types.
    /// </remarks>
    public NativeAotJsonSerializer(JsonSerializerContext context)
    {
        _context = context ?? throw new ArgumentNullException(nameof(context));
        // Cap retained writers at ProcessorCount * 2 (minimum 4).
        // Without a cap, a traffic burst causes the pool to grow unboundedly:
        // every concurrent serialization adds a writer, all are returned after the burst,
        // and none are ever GC'd. Beyond the cap, excess writers are GC'd rather than retained.
        var provider = new Microsoft.Extensions.ObjectPool.DefaultObjectPoolProvider
        {
            MaximumRetained = Math.Max(4, Environment.ProcessorCount * 2)
        };
        _writerPool = provider.Create(new Utf8JsonWriterPooledObjectPolicy());
    }

    /// <inheritdoc/>
    public ReadOnlyMemory<byte> Serialize<TMessage>(TMessage message)
    {
        var typeInfo = TypeInfoCache<TMessage>.GetOrAdd(_context);
        return JsonSerializer.SerializeToUtf8Bytes(message, typeInfo);
    }

    /// <summary>
    /// Serializes the specified message directly into the provided buffer writer without allocating an intermediate <c>byte[]</c>.
    /// </summary>
    /// <remarks>
    /// This is the preferred path for <see cref="DefaultOutbox"/> when writing to its <c>ThreadStatic</c> payload buffer.
    /// </remarks>
    public void Serialize<TMessage>(TMessage message, IBufferWriter<byte> buffer)
    {
        var typeInfo = TypeInfoCache<TMessage>.GetOrAdd(_context);

        var writer = _writerPool.Get();
        try
        {
            writer.Reset(buffer);
            JsonSerializer.Serialize(writer, message, typeInfo);
        }
        // Stryker disable all : Untestable pooling mechanics (leaks/GC pressure cannot be easily asserted in unit tests)
        finally
        {
            writer.Reset(System.IO.Stream.Null); // Clear reference to buffer
            _writerPool.Return(writer);
        }
        // Stryker restore all
    }

    /// <inheritdoc/>
    public TMessage Deserialize<TMessage>(ReadOnlySpan<byte> data)
    {
        var typeInfo = TypeInfoCache<TMessage>.GetOrAdd(_context);
        return JsonSerializer.Deserialize(data, typeInfo)!;
    }

    // Stryker disable all : Untestable pooling mechanics
    private sealed class Utf8JsonWriterPooledObjectPolicy : Microsoft.Extensions.ObjectPool.PooledObjectPolicy<Utf8JsonWriter>
    {
        public override Utf8JsonWriter Create() => new Utf8JsonWriter(System.IO.Stream.Null);
        public override bool Return(Utf8JsonWriter obj) => true;
    }
    // Stryker restore all

    // P1-FIX: Generic static cache eliminates the O(1) dictionary lookup overhead of `context.GetTypeInfo(typeof(T))`.
    // It's evaluated exactly once per message type per application lifetime.
    private static class TypeInfoCache<TMessage>
    {
        private static volatile JsonTypeInfo<TMessage>? s_typeInfo;

        public static JsonTypeInfo<TMessage> GetOrAdd(JsonSerializerContext context)
        {
            var cached = s_typeInfo;
            if (cached is not null) return cached;
            
            if (context.GetTypeInfo(typeof(TMessage)) is not JsonTypeInfo<TMessage> typeInfo)
                throw new InvalidOperationException($"Type {typeof(TMessage).Name} is not registered in the JsonSerializerContext.");

            // G4.3 — Benign race documentation:
            // Two threads may both reach this point simultaneously on first call. Both will call
            // context.GetTypeInfo(), which is documented as thread-safe and idempotent (returns
            // the same JsonTypeInfo<TMessage> instance from the generated context's internal table).
            // Both writes to s_typeInfo produce the same value. The volatile write guarantees that
            // any subsequent reader on any thread sees a non-null, fully constructed JsonTypeInfo<T>.
            //
            // We deliberately do NOT use Interlocked.CompareExchange here because:
            // 1. The race window is measured in nanoseconds (JIT compilation + first call only).
            // 2. Both competing values are equivalent (same JsonTypeInfo from same context).
            // 3. The added atomic barrier of CompareExchange would cost more than the race itself.
            // 4. `volatile` is sufficient to ensure cross-thread visibility of the written value.
            s_typeInfo = typeInfo;
            return typeInfo;
        }
    }
}

