// Copyright © Erickson Lopez. MIT License.
using System;
using System.Buffers;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;

namespace EricksonLopez.Outbox.Serialization;

/// <summary>
/// Provides a strict NativeAOT-compatible JSON serializer.
/// It bans runtime reflection completely by requiring a pre-compiled <see cref="JsonSerializerContext"/>.
/// </summary>
public sealed class NativeAotJsonSerializer : IOutboxSerializer
{
    private readonly JsonSerializerContext _context;
    private readonly Microsoft.Extensions.ObjectPool.ObjectPool<Utf8JsonWriter> _writerPool;

    /// <summary>
    /// Initializes a new instance of the <see cref="NativeAotJsonSerializer"/> class.
    /// </summary>
    /// <param name="context">The pre-compiled <see cref="JsonSerializerContext"/> containing type info.</param>
    /// <remarks>
    /// For NativeAOT compatibility without IL2026/IL2057 warnings, the provided <paramref name="context"/>
    /// must be generated by the System.Text.Json source generator and include all message types.
    /// </remarks>
    public NativeAotJsonSerializer(JsonSerializerContext context)
        : this(context, CreateDefaultPool())
    {
    }

    internal NativeAotJsonSerializer(JsonSerializerContext context, Microsoft.Extensions.ObjectPool.ObjectPool<Utf8JsonWriter> writerPool)
    {
        _context = context ?? throw new ArgumentNullException(nameof(context));
        _writerPool = writerPool ?? throw new ArgumentNullException(nameof(writerPool));
    }

    internal static Microsoft.Extensions.ObjectPool.DefaultObjectPoolProvider CreatePoolProvider(int processorCount)
    {
        return new Microsoft.Extensions.ObjectPool.DefaultObjectPoolProvider
        {
            MaximumRetained = Math.Max(4, processorCount * 2)
        };
    }

    internal static Microsoft.Extensions.ObjectPool.ObjectPool<Utf8JsonWriter> CreateDefaultPool()
    {
        var provider = CreatePoolProvider(Environment.ProcessorCount);
        return provider.Create(new Utf8JsonWriterPooledObjectPolicy());
    }

    /// <inheritdoc/>
    public ReadOnlyMemory<byte> Serialize<TMessage>(TMessage message)
    {
        var typeInfo = TypeInfoCache<TMessage>.GetOrAdd(_context);
        return JsonSerializer.SerializeToUtf8Bytes(message, typeInfo);
    }

    /// <summary>
    /// Serializes the specified message directly into the provided buffer writer without allocating an intermediate <c>byte[]</c>.
    /// </summary>
    /// <typeparam name="TMessage">The type of the message being serialized.</typeparam>
    /// <param name="message">The message instance to serialize.</param>
    /// <param name="buffer">The target buffer writer receiving the serialized bytes.</param>
    /// <remarks>
    /// This is the preferred path for <see cref="DefaultOutbox"/> when writing to its <c>ThreadStatic</c> payload buffer.
    /// </remarks>
    public void Serialize<TMessage>(TMessage message, IBufferWriter<byte> buffer)
    {
        var typeInfo = TypeInfoCache<TMessage>.GetOrAdd(_context);

        var writer = _writerPool.Get();
        try
        {
            writer.Reset(buffer);
            JsonSerializer.Serialize(writer, message, typeInfo);
        }
        finally
        {
            writer.Reset(System.IO.Stream.Null); // Clear reference to buffer
            _writerPool.Return(writer);
        }
    }

    /// <inheritdoc/>
    public TMessage Deserialize<TMessage>(ReadOnlySpan<byte> data)
    {
        var typeInfo = TypeInfoCache<TMessage>.GetOrAdd(_context);
        return JsonSerializer.Deserialize(data, typeInfo)!;
    }

    internal sealed class Utf8JsonWriterPooledObjectPolicy : Microsoft.Extensions.ObjectPool.PooledObjectPolicy<Utf8JsonWriter>
    {
        public override Utf8JsonWriter Create() => new Utf8JsonWriter(System.IO.Stream.Null);
        public override bool Return(Utf8JsonWriter obj) => true;
    }

    // Generic static cache eliminates the O(1) dictionary lookup overhead of `context.GetTypeInfo(typeof(T))`.
    private static class TypeInfoCache<TMessage>
    {
        private static volatile JsonTypeInfo<TMessage>? s_typeInfo;

        public static JsonTypeInfo<TMessage> GetOrAdd(JsonSerializerContext context)
        {
            var cached = s_typeInfo;
            if (cached is not null) return cached;

            var typeInfo = context.GetTypeInfo(typeof(TMessage)) as JsonTypeInfo<TMessage>;
            if (typeInfo is null)
                throw new InvalidOperationException($"Type {typeof(TMessage).Name} is not registered in the JsonSerializerContext.");

            s_typeInfo = typeInfo;
            return typeInfo;
        }
    }
}

