// Copyright © Erickson Lopez. MIT License.
using System;
using System.Data;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using EricksonLopez.Outbox;
using EricksonLopez.Outbox.Generated; // UseGeneratedTypes() extension — auto-generated by [OutboxMessage] source generator
using EricksonLopez.Outbox.Hosting;
using EricksonLopez.Outbox.Persistence;
using EricksonLopez.Outbox.Pipeline;
using EricksonLopez.Outbox.Storage.PostgreSql;
using EricksonLopez.Result;
using Microsoft.AspNetCore.Diagnostics.HealthChecks;
using Microsoft.EntityFrameworkCore;
using Npgsql;
using OpenTelemetry.Metrics;
using OpenTelemetry.Resources;
using OpenTelemetry.Trace;
using Sample.OrderService.Endpoints;
using Sample.OrderService.Infrastructure;
using Sample.OrderService.Infrastructure.Customization;

var builder = WebApplication.CreateBuilder(args);

// =========================================================================
// 0. Preparation: Swagger and API Services
// =========================================================================
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new() 
    { 
        Title = "EricksonLopez.Outbox Showcase", 
        Version = "v1",
        Description = "The ultimate guide project to use the Outbox library, from scratch to advanced." 
    });
});

// =========================================================================
// 0.1. Observability (OpenTelemetry)
// =========================================================================
builder.Services.AddOpenTelemetry()
    .ConfigureResource(resource => resource.AddService("Sample.OrderService"))
    .WithTracing(tracing => tracing
        .AddAspNetCoreInstrumentation()
        .AddHttpClientInstrumentation()
        .AddNpgsql()
        .AddOtlpExporter())
    .WithMetrics(metrics => metrics
        .AddAspNetCoreInstrumentation()
        .AddHttpClientInstrumentation()
        .AddOtlpExporter());

// =========================================================================
// 1. Database Configuration
// =========================================================================
var connectionString = builder.Configuration.GetConnectionString("Postgres")
    ?? "Host=localhost;Database=outbox_showcase;Username=postgres;Password=postgres";

// =========================================================================
// 1.1. Health Checks
// =========================================================================
builder.Services.AddHealthChecks()
    .AddNpgSql(connectionString)
    .AddOutbox(warningThreshold: 500); // Degraded if >500 pending messages, Unhealthy if the dispatcher stopped

// a) ADO.NET Registration (Required for pure ADO.NET)
builder.Services.AddSingleton(_ => NpgsqlDataSource.Create(connectionString));

// b) MediatR
builder.Services.AddMediatR(cfg => cfg.RegisterServicesFromAssembly(typeof(Program).Assembly));

// c) EF Core Interceptor for Domain Events
builder.Services.AddScoped<Sample.OrderService.Infrastructure.Interceptors.PublishDomainEventsInterceptor>();

// d) EF Core Registration with the Interceptor
builder.Services.AddDbContext<AppDbContext>((sp, options) =>
{
    var interceptor = sp.GetRequiredService<Sample.OrderService.Infrastructure.Interceptors.PublishDomainEventsInterceptor>();
    options.UseNpgsql(connectionString).AddInterceptors(interceptor);
});

// =========================================================================
// 2. Outbox Repositories
// =========================================================================
// Configures the repositories that will execute the SQL for insertion and reading.
// Note: We use Postgres in this sample. For SQL Server, use `SqlServerOutboxRepository`.
builder.Services.AddScoped<IOutboxRepository, PostgreSqlOutboxRepository>();

builder.Services.AddScoped<IDeadLetterRepository, PostgreSqlDeadLetterRepository>();

// =========================================================================
// 3. The Broker (Publisher)
// =========================================================================
// Here you inject your real Broker (RabbitMQ, Kafka, Azure Service Bus, MassTransit, etc.)
// In this showcase, we inject ConsoleBrokerPublisher which prints to the console
// so the project runs without depending on external Docker containers.
builder.Services.AddSingleton<IBrokerPublisher, ConsoleBrokerPublisher>();

// =========================================================================
// 3.1. Dispatch Pipeline Middlewares (Level 8 — Customization)
// =========================================================================
// Middlewares are registered in DI as IOutboxMiddleware and are resolved
// by the OutboxChannel to assemble the dispatch pipeline.
// Registration order = execution order in the pipeline.
//
// OPTIMIZATION: If ALL middlewares are Singleton, enable:
//   options.HasOnlySingletonMiddlewares = true; (in AddOutboxDispatcher)
// This caches the pipeline per batch and eliminates construction allocations.
builder.Services.AddSingleton<IOutboxMiddleware, TelemetryOutboxMiddleware>();    // Observes and measures
builder.Services.AddSingleton<IOutboxMiddleware, MessageFilterMiddleware>();       // Can short-circuit
builder.Services.AddSingleton<IOutboxMiddleware, HeaderEnrichmentMiddleware>();    // Enriches headers
builder.Services.AddSingleton<EricksonLopez.Outbox.Diagnostics.IErrorSanitizer, CustomErrorSanitizer>();

// =========================================================================
// 3.2. ManualOutboxDispatcher (Level 9 — Extensions)
// =========================================================================
// ManualOutboxDispatcher allows dispatching messages on demand,
// without depending on the BackgroundService. Useful for:
//   - Serverless functions (Azure Functions, AWS Lambda)
//   - Periodic cron jobs
//   - Administration endpoints that force a drain of the outbox
// Manual registration — it is not registered in AddOutbox() nor AddOutboxDispatcher().
builder.Services.AddScoped<ManualOutboxDispatcher>();

// =========================================================================
// 4. Outbox Core Injection
// =========================================================================
// AddOutbox() injects the `IOutbox` interface and `IOutboxMessageBuilder` 
// that we will use to publish messages in our business code.
//
// UseGeneratedTypes() registers the type resolver.
// UseSerializer(new NativeAotJsonSerializer(...)) registers the STJ-based serializer.
builder.Services.AddOutbox(options =>
{
    options.UseGeneratedTypes(); 
    options.UseSerializer(new EricksonLopez.Outbox.Serialization.NativeAotJsonSerializer(OutboxJsonContext.Default));
});

// =========================================================================
// 5. Dispatcher Configuration (Background Daemon)
// =========================================================================
// The Outbox Dispatcher is a BackgroundService that periodically looks for
// messages in 'Pending' state, and publishes them through the IBrokerPublisher.
// IPollerWakeup (registered by AddOutboxDispatcher) allows waking up the poller
// manually from external code (endpoints, cron jobs, integrations).
builder.Services.AddOutboxDispatcher(options =>
{
    options.BatchSize = 100;                                    // Max messages per scan
    options.PollingInterval = TimeSpan.FromMilliseconds(500);   // Polling when DB is empty
    options.UseAdaptivePolling = true;                          // 0ms when there are messages, 500ms when empty
    options.MaxDegreeOfParallelism = Math.Min(Environment.ProcessorCount, 8); // Parallel consumers
    options.ChannelCapacity = 1000;                             // Backpressure of the internal channel
    options.MaxBatchesPerSecond = 0;                            // 0 = no rate limit (adjust in production)
    options.MaxRetryCount = 10;                                 // Dead-letter after 10 failures
    options.ReclaimTimeout = TimeSpan.FromMinutes(5);           // Crash recovery: reclaim after 5 min
    options.ReclaimInterval = TimeSpan.FromMinutes(1);          // Frequency of the reclamation job
    options.DbRetryMaxAttempts = 3;                             // Retries for transient DB operations
    options.DbRetryBaseDelayMs = 50;                            // Linear delay: attempt * 50ms
    options.HasOnlySingletonMiddlewares = true;                 // All Showcase middlewares are Singleton
});

// =========================================================================
// 6. Inbox Configuration and Cleanup (Background Daemon)
// =========================================================================
// The Inbox daemon is in charge of deleting processed messages (retention)
// and cleaning up old idempotency records.
builder.Services.AddOutboxInbox(options =>
{
    options.RetentionPeriod = TimeSpan.FromDays(7);        // How long processed records will live in the DB
    options.DuplicateDetectionWindow = TimeSpan.FromDays(30); // Idempotency cleanup
});

var app = builder.Build();

// =========================================================================
// 7. Database Initialization and Routes
// =========================================================================

// If it's required to initialize the DB on startup (only for the EF Core Demo)
using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
    // db.Database.EnsureCreated(); // You can enable this if you use a real Postgres
}

app.UseSwagger();
app.UseSwaggerUI(c => c.SwaggerEndpoint("/swagger/v1/swagger.json", "Outbox Showcase v1"));

app.MapHealthChecks("/health", new HealthCheckOptions
{
    ResponseWriter = async (context, report) =>
    {
        context.Response.ContentType = "application/json";
        var result = System.Text.Json.JsonSerializer.Serialize(new
        {
            status = report.Status.ToString(),
            checks = report.Entries.Select(e => new { name = e.Key, status = e.Value.Status.ToString(), description = e.Value.Description })
        });
        await context.Response.WriteAsync(result);
    }
});

// Mapping of the demonstration endpoints (Showcase Levels)
app.MapLevel1QuickStart();
app.MapLevel2Configuration();
app.MapLevel3RealUseCases();
app.MapLevel4AdvancedIntegration();
app.MapLevel5Processing();
app.MapLevel6ErrorHandling();
app.MapLevel7Scalability();
app.MapLevel8Customization();
app.MapLevel9Extensions();
app.MapLevel10InboxIdempotency();
app.MapLevel11Administration();

app.Run();




