<!-- Copyright © Erickson Lopez. MIT License. -->
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <NuGetAudit>false</NuGetAudit>
    <NoWarn>$(NoWarn);CA1305;CS1591;CA1707;CS8618</NoWarn>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="coverlet.msbuild">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="AutoFixture" />
    <PackageReference Include="AutoFixture.AutoNSubstitute" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  

  <ItemGroup>
    <ProjectReference Include="..\..\src\EricksonLopez.Outbox.Dapr\EricksonLopez.Outbox.Dapr.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.Outbox\EricksonLopez.Outbox.csproj" />
  </ItemGroup>
</Project>
