<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Azure Service Bus message broker transport for EricksonLopez.Outbox. Delivers high-performance, Zero-Reflection, NativeAOT-ready event publishing to Azure Service Bus.</Description>
    <PackageTags>$(PackageTags);azure;service-bus;asb;microsoft</PackageTags>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Messaging.ServiceBus" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EricksonLopez.Outbox\EricksonLopez.Outbox.csproj" />
  </ItemGroup>

</Project>
