using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Mvc;
using EricksonLopez.Outbox;
using EricksonLopez.Outbox.Pipeline;
using EricksonLopez.Outbox.Persistence;
using EricksonLopez.Outbox.Serialization;
using EricksonLopez.Outbox.Hosting;
using Sample.OrderService.Infrastructure;
using Sample.OrderService.Infrastructure.Customization;

#pragma warning disable CA1861 // Prefer static readonly fields over constant array arguments

namespace Sample.OrderService.Endpoints;

/// <summary>
/// Level 8 — Customization
/// Demonstrates the implementation and use of replaceable components of the library:
/// IOutboxSerializer, IOutboxMessageTypeResolver, IOutboxMiddleware,
/// OutboxPipeline, and message routing by type (Route/ToPublisher).
/// </summary>
public static class Level8_CustomizationEndpoints
{
    public static void MapLevel8Customization(this IEndpointRouteBuilder app)
    {
        // ─── Endpoint 8a: IOutboxSerializer — custom serialization ───────────
        // IOutboxSerializer defines how messages are serialized to bytes.
        // NativeAotJsonSerializer is the reference implementation based on STJ.
        // You can implement your own (Protobuf, MessagePack, Avro, etc.).
        app.MapGet("/api/level8/serializer", () =>
        {
            return Results.Ok(new
            {
                description = "IOutboxSerializer — serialization contract.",
                methods = new[]
                {
                    new { signature = "ReadOnlyMemory<byte> Serialize<TMessage>(TMessage message)", description = "Serializes to buffer. Returns ReadOnlyMemory<byte> to avoid copies." },
                    new { signature = "void Serialize<TMessage>(TMessage, IBufferWriter<byte>)", description = "Writes directly to the buffer writer. Zero allocations on hot path. Implement for maximum throughput." },
                    new { signature = "TMessage Deserialize<TMessage>(ReadOnlySpan<byte>)", description = "Deserializes from bytes. Currently not used by the dispatcher (which operates on raw bytes), but exposed for external integrations." },
                },
                implementationGuide = new
                {
                    step1 = "Implement IOutboxSerializer with your serialization library.",
                    step2 = "Register in DI: options.UseSerializer(new MySerializer()) or options.UseSerializer<MySerializer>().",
                    step3 = "For NativeAOT: use the overload with instance (options.UseSerializer(instance)), not the generic one.",
                    nativeAotExample = @"
// NativeAotJsonSerializer requires a JsonSerializerContext generated by Source Generators:
[JsonSerializable(typeof(OrderCreatedEvent))]
[JsonSerializable(typeof(OrderConfirmedEvent))]
public partial class OutboxJsonContext : JsonSerializerContext { }

// Then in AddOutbox():
options.UseSerializer(new NativeAotJsonSerializer(OutboxJsonContext.Default));",
                    customExample = @"
// Implementation with Protobuf:
public sealed class ProtobufOutboxSerializer : IOutboxSerializer
{
    public ReadOnlyMemory<byte> Serialize<TMessage>(TMessage message)
    {
        using var ms = new MemoryStream();
        ProtoBuf.Serializer.Serialize(ms, message);
        return ms.ToArray();
    }

    public TMessage Deserialize<TMessage>(ReadOnlySpan<byte> data)
        => ProtoBuf.Serializer.Deserialize<TMessage>(data);
}
// Registration:
options.UseSerializer(new ProtobufOutboxSerializer());"
                }
            });
        })
        .WithSummary("Level 8a - IOutboxSerializer: contract and custom implementation guide")
        .WithTags("Level 8 — Customization");

        // ─── Endpoint 8b: IOutboxMessageTypeResolver — custom type mapping ────
        // IOutboxMessageTypeResolver maps stable aliases (strings in the DB)
        // to CLR types. InMemoryMessageTypeResolver is the manual implementation.
        // The alternative is the Source Generator (UseGeneratedTypes()).
        app.MapGet("/api/level8/type-resolver", (
            [FromServices] IOutboxMessageTypeResolver resolver) =>
        {
            // GetAllMappings() returns the complete registered alias→Type dictionary.
            var mappings = resolver.GetAllMappings();

            // GetAlias<TMessage>() — gets the alias of a registered type.
            // TryGetAlias<TMessage>() — exception-free version.
            // Resolve(alias) — looks up the Type by string alias.
            var resolvedType = resolver.Resolve("order.created.v1");

            return Results.Ok(new
            {
                description = "IOutboxMessageTypeResolver — bidirectional mapping between alias (DB) and CLR types.",
                registeredMappings = mappings.Select(kv => new { alias = kv.Key, clrType = kv.Value.FullName }),
                resolveDemo = new
                {
                    alias = "order.created.v1",
                    resolvedTo = resolvedType?.FullName ?? "null (not registered)"
                },
                methods = new[]
                {
                    "Type? Resolve(string alias) — alias → Type. Null if not found.",
                    "bool TryGetAlias(Type, out string?) — Type → alias. False if not registered.",
                    "bool TryGetAlias<TMessage>(out string?) — generic, more efficient in hot path.",
                    "string GetAlias(Type) — throws InvalidOperationException if not registered.",
                    "string GetAlias<TMessage>() — generic without typeof() in hot path.",
                    "IReadOnlyDictionary<string, Type> GetAllMappings() — all registrations.",
                },
                manualRegistrationExample = @"
// Without Source Generator — manual registration with InMemoryMessageTypeResolver:
var resolver = new InMemoryMessageTypeResolver(new[]
{
    (""order.created.v1"", typeof(OrderCreatedEvent)),
    (""order.confirmed.v1"", typeof(OrderConfirmedEvent)),
});
options.UseTypeResolver(resolver);",
                sourceGeneratorExample = @"
// With Source Generator (recommended):
// 1. Decorate types with [OutboxMessage(""alias"")]:
[OutboxMessage(""order.created.v1"")]
public sealed record OrderCreatedEvent(...);

// 2. Call the generated extension:
options.UseGeneratedTypes(); // automatically generated by EricksonLopez.Outbox.SourceGenerators"
            });
        })
        .WithSummary("Level 8b - IOutboxMessageTypeResolver: GetAlias, Resolve, GetAllMappings")
        .WithTags("Level 8 — Customization");

        // ─── Endpoint 8c: IOutboxMiddleware + OutboxPipeline ─────────────────
        // OutboxPipeline is the class that assembles middlewares into an immutable chain.
        // Demonstrates the manual construction of the pipeline and its 3 Showcase middlewares.
        app.MapGet("/api/level8/middleware-pipeline", (
            [FromServices] IEnumerable<IOutboxMiddleware> middlewares) =>
        {
            var middlewareList = middlewares.ToList();

            return Results.Ok(new
            {
                description = "IOutboxMiddleware + OutboxPipeline — dispatch pipeline ASP.NET Core style.",
                registeredMiddlewares = middlewareList.Select(m => m.GetType().Name).ToList(),
                pipelinePattern = "The pipeline follows the ASP.NET Core delegate pattern: each middleware receives (message, metadata, next, ct). " +
                    "Calling next() continues the chain. NOT calling next() short-circuits the pipeline.",
                middlewareShowcaseTypes = new[]
                {
                    new { type = "TelemetryOutboxMiddleware", pattern = "Observe-and-Pass-Through", description = "Measures dispatch time. Always calls next()." },
                    new { type = "MessageFilterMiddleware", pattern = "Short-Circuit", description = "Blocks specific types. Returns Ok() WITHOUT calling next()." },
                    new { type = "HeaderEnrichmentMiddleware", pattern = "Enrich-and-Pass-Through", description = "Adds headers before dispatch. Calls next() with modified metadata." },
                },
                registrationExample = @"
// Middlewares are registered as IOutboxMiddleware in DI.
// The OutboxChannel resolves them in registration order and builds the pipeline.
services.AddSingleton<IOutboxMiddleware, TelemetryOutboxMiddleware>();
services.AddSingleton<IOutboxMiddleware, MessageFilterMiddleware>();
services.AddSingleton<IOutboxMiddleware, HeaderEnrichmentMiddleware>();

// Optimization: if ALL are Singleton, enable the pipeline cache:
services.AddOutboxDispatcher(options =>
{
    options.HasOnlySingletonMiddlewares = true;
});",
                outboxPipelineApiNote = "OutboxPipeline(middlewares, terminal) builds the chain once. " +
                    "terminal is the OutboxPipelineDelegate that finally calls the IBrokerPublisher."
            });
        })
        .WithSummary("Level 8c - IOutboxMiddleware + OutboxPipeline: construction and patterns")
        .WithTags("Level 8 — Customization");

        // ─── Endpoint 8d: Route/ToPublisher — message routing by type ────
        // OutboxOptions.Route(alias).ToPublisher(publisher) allows directing
        // messages of a specific type to a broker different from the default.
        app.MapGet("/api/level8/message-routing", () =>
        {
            return Results.Ok(new
            {
                description = "OutboxOptions.Route().ToPublisher() — routing of messages by type to different brokers.",
                note = "Routing is configured in AddOutbox() during startup. " +
                    "Messages without an explicit route go to the default broker (UseBroker).",
                routingExample = @"
services.AddOutbox(options =>
{
    // Default broker for all messages
    options.UseBroker<RabbitMQBrokerPublisher>();

    // Specific routing: order.created → Kafka (higher throughput)
    options.Route(""order.created.v1"")
           .ToPublisher(sp => sp.GetRequiredService<KafkaBrokerPublisher>());

    // Routing with direct instance:
    options.Route(""order.confirmed.v1"")
           .ToPublisher(new AzureServiceBusBrokerPublisher(connectionString));

    // Routing with factory:
    options.Route(""order.cancelled.v1"")
           .ToPublisher(sp =>
           {
               var config = sp.GetRequiredService<IOptions<BrokerConfig>>().Value;
               return new RedisBrokerPublisher(config.ConnectionString);
           });
});",
                selectorsAPI = "IBrokerSelector.GetPublisher(messageType) — resolves the publisher for an alias. " +
                    "DefaultBrokerSelector implements this logic: searches in Routes, if not found uses the default."
            });
        })
        .WithSummary("Level 8d - OutboxOptions.Route().ToPublisher(): routing by message type")
        .WithTags("Level 8 — Customization");

        // ─── Endpoint 8e: ITypedBrokerPublisher — strongly typed brokers ────
        // ITypedBrokerPublisher receives the deserialized CLR object instead of raw bytes.
        app.MapGet("/api/level8/typed-publisher", () =>
        {
            return Results.Ok(new
            {
                description = "ITypedBrokerPublisher — strongly typed dispatch.",
                difference = new
                {
                    IBrokerPublisher = "Receives ReadOnlyMemory<byte> payload. Dispatcher does not deserialize. Fastest path.",
                    ITypedBrokerPublisher = "Receives MessageEnvelope<T> containing the deserialized CLR object. Slower, but easier for typed brokers."
                },
                implementationExample = @"
public sealed class TypedBrokerPublisher : ITypedBrokerPublisher
{
    public ValueTask<DispatchResult> PublishAsync<T>(MessageEnvelope<T> message, DispatchContext context)
    {
        Console.WriteLine($""Sending typed message {typeof(T).Name} with CorrelationId {message.Metadata.CorrelationId}"");
        return ValueTask.FromResult(DispatchResult.Ok());
    }
}",
                registrationExample = @"
// Registering a typed publisher is the same as a raw publisher:
options.UseBroker<TypedBrokerPublisher>();
// Or via routing:
options.Route(""order.created.v1"").ToPublisher<TypedBrokerPublisher>();"
            });
        })
        .WithSummary("Level 8e - ITypedBrokerPublisher: routing to typed brokers")
        .WithTags("Level 8 — Customization");

        // ─── Endpoint 8f: IErrorSanitizer — exception redaction ─────────────
        // IErrorSanitizer cleans exceptions before logging them to avoid leaking PII or secrets.
        app.MapGet("/api/level8/error-sanitizer", () =>
        {
            return Results.Ok(new
            {
                description = "IErrorSanitizer — redact exceptions before logging.",
                usage = "Useful to remove Connection Strings or passwords from SQL exceptions.",
                implementationExample = @"
public sealed class CustomErrorSanitizer : IErrorSanitizer
{
    public string Sanitize(Exception exception)
    {
        if (exception.Message.Contains(""Password=""))
        {
            return ""A database error occurred (details redacted for security)."";
        }
        return exception.ToString();
    }
}",
                registrationExample = @"
// In AddOutboxDispatcher:
services.AddOutboxDispatcher(options =>
{
    // The library uses DefaultErrorSanitizer (no-op) by default.
    // Replace it in DI:
    services.AddSingleton<IErrorSanitizer, CustomErrorSanitizer>();
});"
            });
        })
        .WithSummary("Level 8f - IErrorSanitizer: cleaning exceptions")
        .WithTags("Level 8 — Customization");
    }
}
