<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>NATS message broker transport for EricksonLopez.Outbox. Delivers high-performance, Zero-Reflection, NativeAOT-ready event publishing to NATS.</Description>
    <PackageTags>$(PackageTags);nats;broker;pubsub</PackageTags>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NATS.Client.Core" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EricksonLopez.Outbox\EricksonLopez.Outbox.csproj" />
  </ItemGroup>

</Project>
